name: flutter_unity_builder
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: ^1.8.2
  pubspec_yaml: ^3.1.0
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
